--- arch/arm/mach-pxa/Makefile	2007-08-31 14:21:01.000000000 +0800
+++ arch/arm/mach-pxa/Makefile	2011-01-27 22:19:57.021516203 +0800
@@ -31,6 +31,7 @@
 # Misc features
 obj-$(CONFIG_PM) += pm.o sleep.o
 obj-$(CONFIG_PXA_SSP) += ssp.o
+obj-$(CONFIG_KGDB_PXA_SERIAL) += kgdb-serial.o
 
 ifeq ($(CONFIG_PXA27x),y)
 obj-$(CONFIG_PM) += standby.o
